spring.application.name=subject

server.port=8080

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/testdb
spring.datasource.username=green
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#JWT
jwt.secret=rkskekfkakqktkdkwkckzkxkvkgk1a2b3c4d5e6f7g7h8i9j
jwt.expiration=3600000